const members = [
  {
    id: 1,
    name: 'Scott Kunian',
    email: 'skunian@yahoo.com',
    phone: '617-593-2075',
    image: '/images/scott.jpg',
    discord: 'DarthMe',
  },
  {
    id: 2,
    name: 'Paul Moore',
    email: 'paul@example.com',
    phone: '987-654-3210',
    image: '/images/paul.jpg',
    discord: 'PaulM#5678',
  },
  {
    id: 3,
    name: 'Bill Natola',
    email: 'bill@example.com',
    phone: '123-456-7890',
    image: '/images/bill.jpg',
    discord: 'BillN#9012',
  },
  {
    id: 4,
    name: 'Dan Weiner',
    email: 'dan@example.com',
    phone: '987-654-3210',
    image: '/images/dan.jpg',
    discord: 'DanW#3456',
  },
  {
    id: 5,
    name: 'Mario Smith-Pignone',
    email: 'mario@example.com',
    phone: '123-456-7890',
    image: '/images/mario.jpg',
    discord: 'MarioSP#7890',
  },
  {
    id: 6,
    name: 'Nick Mambuca',
    email: 'nick@example.com',
    phone: '987-654-3210',
    image: '/images/nick.jpg',
    discord: 'NickM#2345',
  },
  {
    id: 7,
    name: 'Joe Ettl',
    email: 'joe@example.com',
    phone: '123-456-7890',
    image: '/images/joe.jpg',
    discord: 'JoeE#6789',
  },
  {
    id: 8,
    name: 'Alan Hebert',
    email: 'alan@example.com',
    phone: '987-654-3210',
    image: '/images/alan.jpg',
    discord: 'AlanH#0123',
  },
  {
    id: 9,
    name: 'Mike Amthor',
    email: 'mike@example.com',
    phone: '123-456-7890',
    image: '/images/mike.jpg',
    discord: 'MikeA#4567',
  },
];

module.exports = members;